// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjpvnMfqx8OfEA6irPYGwej7zk6IBhvYM',
    appId: '1:343215923104:web:b7cfc1c170e8df2b9fcec5',
    messagingSenderId: '343215923104',
    projectId: 'grad2-e28bb',
    authDomain: 'grad2-e28bb.firebaseapp.com',
    storageBucket: 'grad2-e28bb.firebasestorage.app',
    measurementId: 'G-ZHNXEQKW2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3tjMB16wjOUAeHJGKZmzulYl3a33c-KQ',
    appId: '1:343215923104:android:e7b65a3a37d414849fcec5',
    messagingSenderId: '343215923104',
    projectId: 'grad2-e28bb',
    storageBucket: 'grad2-e28bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCab0XaMi6vSsjsz2enmwiyNRNc2k5SOqI',
    appId: '1:343215923104:ios:b08a2d035aa9fe269fcec5',
    messagingSenderId: '343215923104',
    projectId: 'grad2-e28bb',
    storageBucket: 'grad2-e28bb.firebasestorage.app',
    iosBundleId: 'com.example.nour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCab0XaMi6vSsjsz2enmwiyNRNc2k5SOqI',
    appId: '1:343215923104:ios:b08a2d035aa9fe269fcec5',
    messagingSenderId: '343215923104',
    projectId: 'grad2-e28bb',
    storageBucket: 'grad2-e28bb.firebasestorage.app',
    iosBundleId: 'com.example.nour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjpvnMfqx8OfEA6irPYGwej7zk6IBhvYM',
    appId: '1:343215923104:web:0830c58db83dbdf19fcec5',
    messagingSenderId: '343215923104',
    projectId: 'grad2-e28bb',
    authDomain: 'grad2-e28bb.firebaseapp.com',
    storageBucket: 'grad2-e28bb.firebasestorage.app',
    measurementId: 'G-WLSY1Z4W2S',
  );
}
