import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // auto-generated by FlutterFire CLI
import 'pages/LoginPage.dart';
import 'pages/resumescreening.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'REBOTA HR App',
      initialRoute: '/',
      routes: {
        '/': (context) => const LoginPage(),
        '/resume': (context) => const ResumeScreeningPage(),
      },
    );
  }
}
